name: Export Addon to Kodi Repository

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'service.libreelec.backupper/addon.xml'
      - 'service.libreelec.backupper/service.py'
      - 'service.libreelec.backupper/addon.py'
      - 'service.libreelec.backupper/resources/**'
      - '.github/workflows/export-addon.yml'

jobs:
  export-addon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LibreELEC Backupper
        uses: actions/checkout@v4

      - name: Checkout Kodi Repository
        uses: actions/checkout@v4
        with:
          repository: Nigel1992/kodi-repository
          path: kodi-repo
          token: ${{ secrets.REPO_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Get version from addon.xml
        id: get_version
        run: |
          VERSION=$(python3 -c "from xml.etree import ElementTree as ET; tree = ET.parse('service.libreelec.backupper/addon.xml'); root = tree.getroot(); print(root.get('version'))")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Delete existing addon files
        run: |
          rm -rf kodi-repo/repository.nigel1992/addons/service.libreelec.backupper/*

      - name: Copy addon files
        run: |
          cp -r service.libreelec.backupper/* kodi-repo/repository.nigel1992/addons/service.libreelec.backupper/

      - name: Commit and push changes
        run: |
          cd kodi-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add repository.nigel1992/addons/service.libreelec.backupper
          git commit -m "Update LibreELEC Backupper to version ${{ steps.get_version.outputs.version }}"
          git push
