name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kodi-addon-checker
          
      - name: Run addon-check
        run: |
          kodi-addon-checker --branch matrix
          
      - name: Create zip file
        run: |
          cd ..
          zip -r service.libreelec.backupper.zip service.libreelec.backupper -x "*.git*" "*.github*" "*.gitignore" "*.DS_Store"
          
      - name: Get version from addon.xml
        id: get-version
        run: |
          VERSION=$(grep -oP '<addon id="service.libreelec.backupper" name="LibreELEC Backupper" version="\K[^"]+' service.libreelec.backupper/addon.xml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ../service.libreelec.backupper.zip
          name: v${{ steps.get-version.outputs.version }}
          body: |
            ## LibreELEC Backupper v${{ steps.get-version.outputs.version }}
            
            ### How to install
            - Download the zip file
            - In Kodi, go to Add-ons > Install from zip file
            - Select the downloaded zip file
            
            ### Changes in this version
            Please see the changelog in addon.xml for details.
          draft: false
          prerelease: false 